name: flutter_rules_practice
description: "Flutter frontend for the War Room Rules Practice incident dashboard."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  http: ^1.6.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true